[package]
name = "never11"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["handleapi", "namedpipeapi", "processenv", "synchapi", "winerror", "winreg", "minwindef"] }
